# Generated by Django 4.2.1 on 2023-05-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_booking_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seats",
            name="cost",
            field=models.IntegerField(default=0),
        ),
    ]
