# Generated by Django 4.2.1 on 2023-05-16 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_seats_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seats",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.booking",
            ),
        ),
    ]
